allTables:
  
  Sessions:
    _totalByes: 192
    gId:
      _isPartitionKey: true
      _fieldNameBytes: 3
      _valueBytes: 24 # 24-char string = 24B
      _totalBytes: 27
    sessionId:
      _isSortKey: true
      _fieldNameBytes: 3
      _valueBytes: 10 # 10-char session key = 10B
      _totalBytes: 13
    wsConnectionId:
      _fieldNameBytes: 14
      _valueBytes: 128 # this is just a very safe estimate; ws connId length is arbitrarily changeable by AWS
      _totalBytes: 142
    ttl:
      _fieldNameByes: 3
      _valueBytes: 7 # 12 digit number + 1 = 6 + 1 = 7B
      _totalBytes: 10
      
  
  Games:
    _define.CommonFields:
      _totalBytes: 50
      gId:
        _isPartitionKey: true
        _fieldNameBytes: 3
        _valueBytes: 24 # 24-char string = 24B
        _totalBytes: 27
      pag:
        _isSortKey: true
        _fieldNameBytes: 3
        _valueBytes: 5 # 5-char string <'//NDX' | '//da0' | '//da1' | '//da2'> = 5B
        _totalBytes: 8
      ttl:
        _fieldNameBytes: 3
        _valueBytes: 7 # 12 digit number + 1 = 6 + 1 = 7B
        _totalBytes: 10
      ver:
        _fieldNameBytes: 3
        _valueBytes: 2 # 2 digit number + 1 = 1 + 1 = 2B
        _totalBytes: 5
        
    _define.SeatFields:
      _totalBytes: 76
      _collection: "map"
      _fieldNameBytes: 2
      _mapOverhead: 3
      pac: # The booster from which a seated player is considering their pick / upgrade.
        _keyOverhead: 1
        _keyNameBytes: 3
        _valueBytes: 24 # max 16 card identities (base64-encoded), using 12bits each = 192bits or 24B
        _totalBytes: 28
      mov: # Locked-in intended move of the seated player.
        _keyOverhead: 1
        _keyNameBytes: 3
        _valueBytes: 34 # r<2-dig number>t<2-dig number>PIK<card-2ch>UPG<card-2ch>REQ<3 or fewer cards - 6ch>DEL<3 or fewer cards - 6ch> = 34B
        _totalBytes: 38
      own: # The cards that the seated player has added to their pool this round (i.e. this booster pack).
        _keyOverhead: 1
        _keyNameBytes: 3
        _valueBytes: 1 # Coded as 1 because as this grows from 0B, the 'pac' field must shrink by the same amt
        _totalBytes: 5


    //NDX: # index page, contains configuration, game settings, and fields that may be indexed
      _totalBytes: 821
      _include.CommonFields: 50
      gamName:
        _isGsiKey: true
        _fieldNameBytes: 7
        _valueBytes: 40 # <'OPEN' | 'CLOS'>#<tcg-4ch>#<ruleset-author-10ch>#<ruleset-name-10ch>#<partial-partitionKey-8ch> = 40B
        _totalBytes: 47
      passwd:
        _fieldNameBytes: 6
        _valueBytes: 6 # 6-char word = 6B
        _totalBytes: 12
      maxSz:
        _fieldNameBytes: 5
        _valueBytes: 2 # 2 digit number + 1 = 1 + 1 = 2B
        _totalBytes: 7
      tcg:
        _fieldNameBytes: 3
        _valueBytes: 4 # value <'MAGI' | 'PKMN' | 'YUGI' | 'SCRY'> = 4B
        _totalBytes: 7
      leadr:
        _fieldNameBytes: 5
        _valueBytes: 10 # value 10-char key (references a full sessionId, not an alias) = 10B
        _totalBytes: 15
      desc:
        _fieldNameBytes: 4
        _valueBytes: 200 # 50-char utf8 = 200B
        _totalBytes: 204
      aliases: # Pool of session aliases that have been used. (We check this to avoid collision when generating new aliases)
        _collection: "set"
        _fieldNameBytes: 7
        _numVals: 8
        _valueBytes: 3 # 3-char session alias = 3B
        _totalBytes: 29
      sesns: # Tracks which sessions exist for the draft and which aliases they map to
        _collection: "map"
        _fieldNameBytes: 5
        _mapOverhead: 3
        _numKeys: 8
        _perMapping:
          _keyOverhead: 1
          _keyNameBytes: 10 # 10-char session key = 10B
          _valueBytes: 3 # 3-char session alias = 3B
        _totalBytes: 122
      playrNames:
        _collection: "map"
        _fieldNameBytes: 10
        _mapOverhead: 3
        _numKeys: 8
        _perMapping:
          _keyOverhead: 1
          _keyNameBytes: 3 # 3-char session alias = 3B
          _valueBytes: 20 # 20-char ascii (or 5-char max-size utf8) playername = 20B
        _totalBytes: 205
      seats: # Where different players are sitting
        _collection: "map"
        _fieldNameBytes: 5
        _mapOverhead: 3
        _numKeys: 8
        _perMapping:
          _keyOverhead: 1
          _keyNameBytes: 2 # s<number> = 2chars = 2B# 3-char session alias = 3B
          _valueBytes: 3 # 3-char session alias = 3B
        _totalBytes: 56
      seated: # Seated player aliases (to check for duplicates when new players attempt to sit down)
        _collection: "set"
        _fieldNameBytes: 6
        _numValues: 8
        _valueBytes: 3 # 3-char session alias = 3B
        _totalBytes: 30
      ready: # Players who are seated and satisfied with game settings
        _collection: "set"
        _fieldNameBytes: 8
        _numValues: 8
        _valueBytes: 10 # 3-char session alias = 3B
        _totalBytes: 32
      init: # Boolean: Is the game started? This should only be set as part of a multi-page transaction
        _fieldNameVals: 4
        _valueBytes: 1
        _totalBytes: 5

    //da0: # data 0 -- for the most frequent gamestate writes, that should spend only 1 WCU. Also includes some game settings.
      _totalBytes: 898
      _include.CommonFields: 50
      rulesetId:
        _fieldNameBytes: 9
        _valueBytes: 8 # value 8-char string = 8B
        _totalBytes: 17
      xtensns:
        _collection: "set"
        _fieldNameBytes: 7
        _numVals: 15
        _valueBytes: 11 # <2-char sort key prefix>#<8-char extension name> = 11B
        _totalBytes: 172
      timeLimtScheme: # Structure of how turns are timed. Note that the max delay is 900s (15min) due to SQS limitations.
        _fieldNameBytes: 14
        _valueBytes: 17 # <'NONE' | 'FLAT_XXXs' | 'DESC_XXXs_TO_XXXs'> = max 17B.
        _totalBytes: 31
      init: # Boolean: Is the game started? This should only be set as part of a multi-page transaction
        _fieldNameVals: 4
        _valueBytes: 1
        _totalBytes: 5
      roundTurn:
        _fieldNameBytes: 9
        _valueBytes: 6 # r<2-dig number>t<2-dig number> (r stands for round, t for turn)
        _totalBytes: 15
      # s0 through s9 represent seats and the resources assigned to them. These update often.
      s0:
        _include.SeatFields: 76
      s1:
        _include.SeatFields: 76
      s2:
        _include.SeatFields: 76
      s3:
        _include.SeatFields: 76
      s4:
        _include.SeatFields: 76
      s5:
        _include.SeatFields: 76
      s6:
        _include.SeatFields: 76
      s7:
        _include.SeatFields: 76
      
    //da1: # data 1 -- for relatively infrequent writes
      _totalBytes: 1017
      _include.CommonFields: 50
      pacsBlok: #unopened packs, encoded as a base64 block, each card takes 12 bits
        _fieldNameBytes: 8
        _valueBytes: 720
        _totalBytes: 728
      colsBlok: #player collections, encoded as a base64 block, each card takes 12 bits
        _fieldNameBytes: 8
        _valueBytes: 1 # This grows from 0 to 720 exactly as pacsBlok shrinks to 0, between rounds
        _totalBytes: 9
      shop1: #upgrade store, encoded as a base64 block: each (card and associated inventory) takes 18 bits; 100 upgrades can be encoded this way here
        _fieldNameBytes: 5
        _valueBytes: 225
        _totalBytes: 230

    //da2: # data 2 -- for relatively infrequent writes
      _totalBytes: 1018
      _include.CommonFields: 50
      shop2: #upgrade store, encoded as a base64 block: each (card and associated inventory) takes 18 bits; 428 upgrades can be encoded this way here
        _fieldNameBytes: 5
        _valueBytes: 963
        _totalBytes: 968
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
